<a href="https://colab.research.google.com/github/yauzaa/Data-Analysis/blob/main/NumPy_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Массивы NumPy



In [ ]:
import numpy as np

In [ ]:
mylist = [1, 2, 3]

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [ ]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
len(np.linspace(0, 5, 21))

21

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5, 2) # random number

array([[0.97791191, 0.61159951],
       [0.94628427, 0.43289654],
       [0.79182632, 0.45650246],
       [0.82667814, 0.14623959],
       [0.60263149, 0.591275  ]])

In [ ]:
np.random.randn(2,3)

array([[-0.39682137, -2.89835198,  0.76999556],
       [ 0.546213  ,  1.16893157,  0.98804578]])

In [ ]:
np.random.randint(0, 101, (4,5))

array([[ 0, 12, 17, 75, 79],
       [97, 93, 24, 36, 63],
       [19, 35, 30, 10, 60],
       [20, 27,  8, 86, 26]])

In [ ]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [ ]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5, 5) # reshape to matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [ ]:
ranarr.max()

92

In [ ]:
ranarr.min()

4

In [ ]:
ranarr.argmax() # [1] max position in ranarr

7

In [ ]:
ranarr.argmin() # [5] min position in ranarr

3

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

## Индексация и выбор данных из массивов NumPy


In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5] = 100 # broadcasting
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_array = arr[:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
array_copy = arr.copy()

In [ ]:
array_copy[:] = 100
array_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
array_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
array_2d.shape

(3, 3)

In [ ]:
array_2d[0]

array([ 5, 10, 15])

In [ ]:
array_2d[2]

array([35, 40, 45])

In [ ]:
array_2d[1][1] # --

25

In [ ]:
array_2d[1,1] # --

25

In [ ]:
array_2d[0,2]

15

In [ ]:
array_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_array = arr>4

In [ ]:
arr[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>4] # conditional selection

array([ 5,  6,  7,  8,  9, 10])

## Операции в NumPy

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
1 / arr

<ipython-input-178-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.max()

9

In [ ]:
arr.var()

8.25

In [ ]:
arr.std() # среднеквадратичное отклонение

2.8722813232690143

In [ ]:
arr2d = np.arange(0,25).reshape(5,5)

In [ ]:
arr2d.shape

(5, 5)

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d.sum()

300

In [ ]:
arr2d.sum(axis=0) # сумма колонки

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis=1) # сумма строк

array([ 10,  35,  60,  85, 110])

In [ ]:
array = np.linspace(0, 1, 20)
array


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])